name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/anaismoreaugeo/hello-docker-gcr-demo:staging
          docker run ghcr.io/anaismoreaugeo/hello-docker-gcr-demo:staging
          docker push ghcr.io/anaismoreaugeo/hello-docker-gcr-demo:staging